apiVersion: v2
name: matrix-admin-bot
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: common
  version: "0.2.2"
  repository: "https://paritytech.github.io/helm-charts/"
